# Generated by Django 4.1 on 2023-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=100)),
                ('task_desc', models.TextField()),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
